; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
AppName=Winget Dashboard Agent
AppVersion=1.1.0
AppPublisher=Twoja Firma
DefaultDirName={commonappdata}\WingetAgent
OutputBaseFilename=WingetDashboardAgent_Setup
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible

[Files]
Source: "C:\Users\Administrator\PycharmProjects\winget-dashboard_new\agent_builds\agent.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\PycharmProjects\winget-dashboard_new\agent_builds\ui_helper.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\PycharmProjects\winget-dashboard_new\agent_builds\updater.exe"; DestDir: "{app}"; Flags: ignoreversion

[Run]
; Instaluje i uruchamia usługę systemową agent.exe
Filename: "{app}\agent.exe"; Parameters: "install"; StatusMsg: "Instalowanie usługi..."; Flags: runhidden waituntilterminated
Filename: "sc"; Parameters: "config WingetDashboardAgent start=auto"; StatusMsg: "Konfigurowanie usługi..."; Flags: runhidden waituntilterminated
Filename: "sc"; Parameters: "start WingetDashboardAgent"; StatusMsg: "Uruchamianie usługi..."; Flags: runhidden waituntilterminated

; Tworzy zadanie w Harmonogramie (już działa obowiązkowo i w tle)
Filename: "schtasks.exe"; Parameters: "/Create /TN ""Winget Dashboard UI Helper"" /TR ""'{app}\ui_helper.exe'"" /SC ONLOGON /RL HIGHEST /RU ""NT AUTHORITY\SYSTEM"" /F"; Flags: runhidden

; POPRAWKA: Usunięto "Description", aby polecenie było obowiązkowe i niewidoczne dla użytkownika
Filename: "{app}\ui_helper.exe"; Flags: nowait postinstall runascurrentuser

[UninstallRun]
Filename: "schtasks.exe"; Parameters: "/Delete /TN ""Winget Dashboard UI Helper"" /F"; Flags: runhidden waituntilterminated; RunOnceId: "delete_schedule_task"
Filename: "sc"; Parameters: "stop WingetDashboardAgent"; Flags: runhidden waituntilterminated; RunOnceId: "stop_service"
Filename: "{app}\agent.exe"; Parameters: "remove"; Flags: runhidden waituntilterminated; RunOnceId: "remove_service"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
